Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -41,6 +41,11 @@ jobs:
     if: startsWith(github.ref, 'refs/tags/v')
     steps:
       - uses: actions/checkout@v4
+      - name: Echo context
+        run: |
+         echo "GITHUB_REF = $GITHUB_REF"
+         echo "GITHUB_SHA = $GITHUB_SHA"
+         echo "TAG = ${GITHUB_REF#refs/tags/}"
 
       - name: Set up Ruby
         uses: ruby/setup-ruby@v1
@@ -49,10 +54,28 @@ jobs:
           bundler-cache: true
 
       - name: Build gem
-        run: bundle exec rake build
+        run: |
+          # load versipn from code 
+          version=$(ruby -e "require './lib/webgem/version'; puts Webgem::VERSION")
+          tag=${GITHUB_REF#refs/tags/}
+
+          echo "Gem version: $version"
+          echo "Tag: $tag"
+           i
+           f [ "v$version" != "$tag" ]; then
+          echo "ERROR: tag ($tag) does not match gem version (v$version)"
+          exit 1
+          fi
+
+          bundle exec  racke build
+          
+
 
       - name: Publish to RubyGems
         env:
           RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
         run: |
-          gem push pkg/${GEM_NAME}-$(ruby -e "require './lib/webgem/version'; puts Webgem::VERSION").gem
+             version=$(ruby -e "require './lib/webgem/version'; puts Webgem::VERSION")
+              gem_file="pkg/${GEM_NAME}-${version}.gem"
+              echo "Publishing $gem_file"
+               ls -lah pkg
